### ISSUE TITLE
Make Prefix Specification

### ISSUE THREAD

**Issue by DomT4** [kfogel/OneTime#11]
Can OneTime be changed to fit make prefix specification?

Currently if you wish to change where it does ``` make install ``` you have to edit the makefile, but this isn't terribly convenient from the command line.

Would it be possible to move towards

```
make install DESTDIR=#{prefix}
```

or 

```
make install prefix=#{prefix}
```

instead?

**Comment by kfogel** [comment]
Thanks!  I see the PR in issue #12, and have commented there about the reason for my delay in responding.
