### ISSUE TITLE
online-mode?

### ISSUE THREAD

**Issue by aaannndddyyy** [kfogel/OneTime#21]
~Maybe there could be an (unauthenticated?) online mode where both sides invoke the program, and enter texts via stdin and upon pressing enter button get the encrypted text back.~
In online mode, the header is printed before the user enters the plain text.
Expected result: an intact OneTime Message is put on the screen.

**Comment by kfogel** [comment]
Someone else can implement this as a wrapper around OneTime, if they want :-).  I'd like to keep the core Python script as simple as possible.

**Comment by aaannndddyyy** [comment]
Ok, i changed it in my fork. It's not very nice, but it does the job for me. Though, maybe I will change it as to no require any header at all for using it in instant messaging.
