### ISSUE TITLE
option to disable authentication 

### ISSUE THREAD

**Issue by aaannndddyyy** [kfogel/OneTime#22]
Maybe there could be an option to disable the authentication and maybe even the fuzz, if all you want is message secrecy, but don't worry about authenticity, but do worry about pad usage.
since it'S just a few if statements, this shouldn't complicate the code.

**Comment by kfogel** [comment]
IMHO, that extreme degree of pad conservation is not worth the user-interface complexity (or the code complexity) of supporting this as an option.
