### ISSUE TITLE
Link to this doc, if only to explain why it doesn't apply.

### ISSUE THREAD

**Issue by kfogel** [kfogel/OneTime#28]
Link to http://www.2uo.de/myths-about-urandom/ from somewhere, if only to explain why its central point doesn't apply to OneTime.  (It's still an excellent doc about how random numbers are produced on Linux, though.)

(And see also http://juho.tykkala.fi/Randomness-in-Linux.)

**Comment by marianoju** [comment]
I think this issue has been resolved. Currently https://www.red-bean.com/onetime features a link to http://www.2uo.de/myths-about-urandom/.

**Comment by kfogel** [comment]
Thanks, @marianoju.  I hadn't noticed that this was resolved -- I'll close it now.

I haven't had much time to work on OneTime for a while, but at the very least closing this issue ought to be an easy lift :-).
